### ISSUE TITLE
download medicat

### ISSUE THREAD

**Issue by cl-red** [allenai/medicat#7]
Hello, I sent you a download request in the application form of the medicat dataset the day before yesterday, but I still haven't received your reply after 48 hours. Is there any problem? Please let me know, thank you.

**Comment by Diyago** [comment]
Same problem, didnt get any responce. Is there any external dataset?

**Comment by hangyav** [comment]
Hi, I had the same issue. After contacting the authors of the paper via email they shared the data with me within 1-2 day.

**Comment by lucylw** [comment]
If you haven't received the dataset after a week, please email me at lucyw@allenai.org. Sometimes the links wind up in people's spam boxes, so please check there as well.
